excluded:
  - DerivedData
  - Build

disabled_rules:
  - inclusive_language
  - opening_brace

identifier_name:
  min_length:
    warning: 2
  max_length:
    warning: 50

line_length:
  warning: 200

file_length:
  warning: 600

type_body_length:
  warning: 500

function_body_length:
  warning: 120

function_parameter_count:
  warning: 8

cyclomatic_complexity:
  warning: 15
